AriaHands:
  hand_selection: "right"

DINOSAM:
  dinosam_prompt:
    obj1: "a black handle ."
    arm: "human arms . human hands ."

CamTriangulator:
  pose_method:
    obj1: "pca2"
    default: "pca2"

ManiDsGen:
  disable_kinematic_latching_right: true
  disable_kinematic_latching_left: true