AriaHands: 
  hand_selection: "right"
  grasp_threshold: 0.120

DINOSAM:
  dinosam_prompt:
    obj1: "a light beige cup ."
    obj2: "a dark green cup ."
    arm: "human arms . human hands ."

CamTriangulator:
  pose_method:
    obj1: "pca2"
    obj2: "pca2"
    default: "pca2"