AriaHands:
  hand_selection: "right"

DINOSAM:
  dinosam_prompt:
    obj1: "an orange cube ."
    obj2: "a plate ."
    arm: "human arms . human hands ."

CamTriangulator:
  pose_method:
    obj1: "pca1"
    obj2: "pca1"
    default: "pca1"

DatasetGen:
  disable_kinematic_latching_right: false
  disable_kinematic_latching_left: true

DepthLifter:
  pose_method:
    obj1: "pca1"
    obj2: "pca1"
    default: "pca1"
